services:
  proxy:
    image: m0stwan1ed/proxy:1.0
    links:
      - identidock
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PROXY=http://identidock:9090

  identidock:
    image: m0stwan1ed/identidock:newest
    links:
      - dnmonster
      - redis
    environment:
      ENV: PROD

  dnmonster:
    image: amouat/dnmonster:1.0

  redis:
    image: redis:3

  logspout:
    image: amouat/logspout-logstash
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "8000:80"
    links:
      - logstash
    command: logstash://logstash:5000

  logstash:
    image: logstash:1.5
    volumes:
    - ./logstash.conf:/etc/logstash.conf
    environment:
      LOGSPOUT: ignore
    command: -f /etc/logstash.conf
    links: 
      - elasticsearch
    expose:
      - "5000"

  elasticsearch:
    image: elasticsearch:1.7
    environment:
      LOGSPOUT: ignore
    # expose:
    #   - "9200"
  
  kibana:
    image: kibana:4.0
    environment:
      LOGSPOUT: ignore
      ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
      - elasticsearch
    ports:
      - "5601:5601"